### ISSUE TITLE
No space left on device during build of windows/server image

### ISSUE THREAD

**Issue by bonkboykz** [jpribyl/action-docker-layer-caching#53]
**Describe the bug**
Post action job fails to save layers due to space exhaustion

**To Reproduce**
1. Create Dockerfile with base image `FROM mcr.microsoft.com/windows/server:ltsc2022`
2. Run action with `jpribyl/action-docker-layer-caching@v0.1.1` before build

**Expected behavior**
Action caches layers

**Debug logs**
If applicable, add debug logs to help explain your problem.
Learn more about enabling the debug log at https://docs.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging

```
Post job cleanup.
"C:\Program Files\Git\bin\sh.exe" -c "docker save '40bd1f550d19' '40bd1f550d19' 'de89f603a77[2](https://github.com/neuroncapital/guardiola-hub/actions/runs/6767805730/job/18391054360#step:12:2)' '2e[3](https://github.com/neuroncapital/guardiola-hub/actions/runs/6767805730/job/18391054360#step:12:3)de195d27a' 'd526b0e06787' '7679c927f2be' '2d37716c64d7' 'c39c89e5dc58' '96aa4f6f9f35' '235bd49ce46a' '9beb9f2ebd35' '40aaff398e23' '0b2566b4f550' '0e580eef7e40' '8ea0670f4b87' '1663ffd046eb' '1663ffd046eb' '1663ffd046eb' 'gcr.io/ordinal-bucksaw-378907/position-producer:4ee66506644e5581484bf6dd16518f7c312ac118' '40bd1f550d19' 'de89f603a772' '2e3de195d27a' 'd526b0e06787' '7679c927f2be' '2d37716c64d7' 'c39c89e5dc58' '96aa4f6f9f35' '235bd49ce46a' '9beb9f2ebd35' '40aaff398e23' '0b2566b4f550' '0e580eef7e40' '8ea0670f4b87' '1663ffd046eb' 'gcr.io/ordinal-bucksaw-378907/position-producer:latest' '40bd1f550d19' 'de89f603a772' '2e3de195d27a' 'd526b0e06787' '7679c927f2be' '2d37716c64d7' 'c39c89e5dc58' '96aa4f6f9f35' '235bd49ce46a' '9beb9f2ebd35' '40aaff398e23' '0b2566b4f550' '0e580eef7e40' '8ea0670f4b87' '1663ffd046eb' 'ghcr.io/neuroncapital/position-producer:4ee66506644e5581484bf6dd16518f7c312ac118' '40bd1f550d19' 'de89f603a772' '2e3de195d27a' 'd526b0e06787' '7679c927f2be' '2d37716c64d7' 'c39c89e5dc58' '96aa4f6f9f35' '235bd49ce46a' '9beb9f2ebd35' '40aaff398e23' '0b2566b4f550' '0e580eef7e40' '8ea0670f4b87' '1663ffd046eb' 'ghcr.io/neuroncapital/position-producer:latest' '40bd1f550d19' 'de89f603a772' '2e3de195d27a' 'd526b0e06787' '7679c927f2be' '2d37716c64d7' 'c39c89e5dc58' '96aa4f6f9f35' '235bd49ce46a' '9beb9f2ebd35' '40aaff398e23' '0b2566b4f550' '0e580eef7e40' '8ea0670f4b87' '1663ffd046eb' 'mcr.microsoft.com/windows/server:ltsc2022' '1663ffd046eb' | tar xf - -C ."
tar: 82836898ece039f3e6cfc17a71878f52fb4cf6ed7ab4c665b895f37703dcf95e/layer.tar: Cannot create symlink to '..\\d5fe546169a1ceaa9a1a024e9019797b52dd0e47f78cba331829abdef53f3428\\layer.tar': No space left on device
tar: Exiting with failure status due to previous errors
Error: The process 'C:\Program Files\Git\bin\sh.exe' failed with exit code 2
    at ExecState._setResult (D:\a\_actions\jpribyl\action-docker-layer-caching\v0.1.1\dist\ttsc-dist\post.js\index.js:3208:2[5](https://github.com/neuroncapital/guardiola-hub/actions/runs/6767805730/job/18391054360#step:12:5))
    at ExecState.CheckComplete (D:\a\_actions\jpribyl\action-docker-layer-caching\v0.1.1\dist\ttsc-dist\post.js\index.js:3191:18)
    at ChildProcess.<anonymous> (D:\a\_actions\jpribyl\action-docker-layer-caching\v0.1.1\dist\ttsc-dist\post.js\index.js:3085:27)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:1[6](https://github.com/neuroncapital/guardiola-hub/actions/runs/6767805730/job/18391054360#step:12:6))
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
Error: Error: The process 'C:\Program Files\Git\bin\sh.exe' failed with exit code 2
```

**Runner Environment (please complete the following information):**
 - OS: windows-latest
 - Action version: v0.1.1

**Additional context**

**Comment by angold5** [comment]
I am also having this issue, but on the Linux Github propided runners.

**Comment by owen2345** [comment]
Same here.
